### ISSUE TITLE
[Bug]: Does not load in Castaway

### ISSUE THREAD

**Issue by fan87** [originalnicodr/CinematicUnityExplorer#71]
### Are you on the latest version of CinematicUnityExplorer?

- [X] Yes, I'm on the latest version of CinematicUnityExplorer.

### Which release are you using?

BepInEx IL2CPP

### Which game did this occur on?

Castaway (https://www.castaways.com/)

### Describe the issue.

CinematicUnityExplorer doesn't seem to load with game Castaway

### Relevant log output

```shell
[Message: Preloader] BepInEx 6.0.0-be.688 - Castaways
[Message: Preloader] Built from commit 49015217f3becf052d33fa4658ac19229f5daa3a
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2022.3.11f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [UnityExplorer 1.0.0]
[Message:UnityExplorer] CinematicUnityExplorer 1.0.0 initializing...
[Message:UnityExplorer] [UniverseLib] UniverseLib 1.5.5 initializing...
[Info   :Il2CppInterop] Registered mono type UniverseLib.UniversalBehaviour in il2cpp domain
[Info   :Il2CppInterop] Registered mono type UniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumerator in il2cpp domain
[Message:UnityExplorer] [UniverseLib] Finished UniverseLib initial setup.
[Info   :Il2CppInterop] Registered mono type UnityExplorer.ExplorerBehaviour in il2cpp domain
[Message:UnityExplorer] Initialized UnityCrashPrevention for: Canvas.get_renderingDisplaySize
[Message:   BepInEx] Chainloader startup complete
[Message:UnityExplorer] [UniverseLib] Can't cache type named __c__DisplayClass11_0 Error: System.TypeLoadException: GenericArguments[0], 'Castaways.Game.Actor.HumanVisualAction', on 'Castaways.Game.Actor.BaseActor`1[ActionType]' violates the constraint of type parameter 'ActionType'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[Message:UnityExplorer] [UniverseLib] Loaded Unhollowed modules in 1.618 seconds.
[Message:UnityExplorer] [UniverseLib] Setup deobfuscation cache in 0.098000005 seconds.
[Message:UnityExplorer] [UniverseLib] Initialized new InputSystem support.
[Message:UnityExplorer] [UniverseLib] 	 IL2CPP method has no corresponding pointer, aborting patch of UnityEngine.AssetBundle.UnloadAllAssetBundles
[Info   :Il2CppInterop] Registered mono type UniverseLib.AssetBundle in il2cpp domain
[Message:UnityExplorer] [UniverseLib] Loaded modern bundle for Unity 2022.3.11f1
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.NullReferenceException: Object reference not set to an instance of an object.
   at UniverseLib.Input.InputSystem.AddUIInputModule()
   at UniverseLib.Input.EventSystemHelper.AddUIModule()
   at UniverseLib.UI.UniversalUI.CreateRootCanvas()
   at UniverseLib.UI.UniversalUI.Init()
   at UniverseLib.Universe.SetupCoroutine()+MoveNext()
   at UniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumerator.MoveNext()
   at Trampoline_ByteThisUniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumeratorMoveNext(IntPtr , Il2CppMethodInfo* )
```

**Comment by originalnicodr** [comment]
Hey! Sorry for the delay here, it has been a busy couple of weeks. Would you mind trying [yukieijis fork](https://github.com/yukieiji/UnityExplorer) with the game? To make sure the problem isn't coming from something I did.

Also, since it's an MMO/online game I would have my hopes very high to get this working.

**Comment by fan87** [comment]
Hi, sorry for the delay : /, it has also been really busy to me the past few weeks

> Also, since it's an MMO/online game I would have my hopes very high to get this working.

Yeah that's what I thought

> Would you mind trying [yukieijis fork](https://github.com/yukieiji/UnityExplorer) with the game? To make sure the problem isn't coming from something I did.

Sadly it doesn't work

```
[08:16:29.970] [UnityExplorer] UnityExplorer 4.12.0 initializing...
[08:16:29.983] [UnityExplorer] [UniverseLib] UniverseLib 1.5.6 initializing...
[08:16:29.985] Registered mono type UniverseLib.UniversalBehaviour in il2cpp domain
[08:16:30.306] Registered mono type UniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumerator in il2cpp domain
[08:16:30.503] [UnityExplorer] [UniverseLib] Finished UniverseLib initial setup.
[08:16:30.511] Registered mono type UnityExplorer.ExplorerBehaviour in il2cpp domain
[08:16:30.544] [UnityExplorer] Initialized UnityCrashPrevention for: Canvas.get_renderingDisplaySize
[08:16:35.632] [UnityExplorer] [UniverseLib] Can't cache type named __c__DisplayClass11_0 Error: System.TypeLoadException: GenericArguments[0], 'Il2CppCastaways.Game.Actor.HumanVisualAction', on 'Il2CppCastaways.Game.Actor.BaseActor`1[ActionType]' violates the constraint of type parameter 'ActionType'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm) in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Reflection\ReflectionUtility.cs:line 121
[08:16:39.510] [UnityExplorer] [UniverseLib] Loaded Unhollowed modules in 9.203 seconds.
[08:16:39.603] [UnityExplorer] [UniverseLib] Setup deobfuscation cache in 0.09200001 seconds.
[08:16:39.612] [UnityExplorer] [UniverseLib] Initialized new InputSystem support.
[08:16:39.668] [UnityExplorer] [UniverseLib]     IL2CPP method has no corresponding pointer, aborting patch of UnityEngine.AssetBundle.UnloadAllAssetBundles
[08:16:39.671] Registered mono type UniverseLib.AssetBundle in il2cpp domain
[08:16:39.730] [UnityExplorer] [UniverseLib] Loaded modern bundle for Unity 2022.3.11f1
[08:16:39.748] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.NullReferenceException: Object reference not set to an instance of an object.
   at UniverseLib.Input.InputSystem.AddUIInputModule() in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Input\InputSystem.cs:line 360
   at UniverseLib.Input.EventSystemHelper.AddUIModule() in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Input\EventSystemHelper.cs:line 226
   at UniverseLib.UI.UniversalUI.CreateRootCanvas() in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\UI\UniversalUI.cs:line 171
   at UniverseLib.UI.UniversalUI.Init() in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\UI\UniversalUI.cs:line 110
   at UniverseLib.Universe.SetupCoroutine()+MoveNext() in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Universe.cs:line 130
   at UniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumerator.MoveNext() in D:\a\UnityExplorer\UnityExplorer\UniverseLib\src\Runtime\Il2Cpp\Il2CppManagedEnumerator.cs:line 80
   at Trampoline_ByteThisUniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumeratorMoveNext(IntPtr , Il2CppMethodInfo* )
```
