### ISSUE TITLE
[Bug]: the format is invalid

### ISSUE THREAD

**Issue by 2hac** [originalnicodr/CinematicUnityExplorer#88]
### Are you on the latest version of CinematicUnityExplorer?

- [X] Yes, I'm on the latest version of CinematicUnityExplorer.

### Which release are you using?

BepInEx Unity IL2CPP CoreCLR

### Which game did this occur on?

Its a game i made

### Describe the issue.

Never works.

### Relevant log output

```shell
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2023.2.8f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [UnityExplorer 1.2.0]
[Message:UnityExplorer] CinematicUnityExplorer 1.2.0 initializing...
[Message:UnityExplorer] [UniverseLib] UniverseLib 1.5.5 initializing...
[Info   :Il2CppInterop] Registered mono type UniverseLib.UniversalBehaviour in il2cpp domain
[Info   :Il2CppInterop] Registered mono type UniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumerator in il2cpp domain
[Message:UnityExplorer] [UniverseLib] Finished UniverseLib initial setup.
[Info   :Il2CppInterop] Registered mono type UnityExplorer.ExplorerBehaviour in il2cpp domain
[Message:UnityExplorer] Initialized UnityCrashPrevention for: Canvas.get_renderingDisplaySize
[Message:   BepInEx] Chainloader startup complete
[Message:     Unity] Initialized AudioController
[Message:     Unity] Initialized VFXController
[Message:     Unity] Initialized SpawnableController`1
[Message:UnityExplorer] [UniverseLib] Can't cache type named Type Error: System.TypeLoadException: Could not load type 'UnityEngine.InputForUI.Event' from assembly 'UnityEngine.InputForUIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[Message:UnityExplorer] [UniverseLib] Can't cache type named IMapFn`1 Error: System.TypeLoadException: Could not load type 'UnityEngine.InputForUI.Event' from assembly 'UnityEngine.InputForUIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[Message:UnityExplorer] [UniverseLib] Can't cache type named MethodInfoStoreGeneric_Map_Public_Abstract_Virtual_New_TOutputType_byref_TEventType_0`1 Error: System.TypeLoadException: Could not load type 'UnityEngine.InputForUI.Event' from assembly 'UnityEngine.InputForUIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[Message:UnityExplorer] [UniverseLib] Can't cache type named MapAsObject Error: System.TypeLoadException: Could not load type 'UnityEngine.InputForUI.Event' from assembly 'UnityEngine.InputForUIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[Message:UnityExplorer] [UniverseLib] Can't cache type named MethodInfoStoreGeneric_Map_Public_Virtual_Final_New_IEventProperties_byref_TEventType_0`1 Error: System.TypeLoadException: Could not load type 'UnityEngine.InputForUI.Event' from assembly 'UnityEngine.InputForUIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[Message:UnityExplorer] [UniverseLib] Can't cache type named MapAsEventSource Error: System.TypeLoadException: Could not load type 'UnityEngine.InputForUI.Event' from assembly 'UnityEngine.InputForUIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[Message:UnityExplorer] [UniverseLib] Can't cache type named MethodInfoStoreGeneric_Map_Public_Virtual_Final_New_EventSource_byref_TEventType_0`1 Error: System.TypeLoadException: Could not load type 'UnityEngine.InputForUI.Event' from assembly 'UnityEngine.InputForUIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[Message:UnityExplorer] [UniverseLib] Can't cache type named MapAsEventModifiers Error: System.TypeLoadException: Could not load type 'UnityEngine.InputForUI.Event' from assembly 'UnityEngine.InputForUIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[Message:UnityExplorer] [UniverseLib] Can't cache type named MethodInfoStoreGeneric_Map_Public_Virtual_Final_New_EventModifiers_byref_TEventType_0`1 Error: System.TypeLoadException: Could not load type 'UnityEngine.InputForUI.Event' from assembly 'UnityEngine.InputForUIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[Message:UnityExplorer] [UniverseLib] Can't cache type named MethodInfoStoreGeneric_Map_Private_TOutputType_TMapType_0`2 Error: System.TypeLoadException: Could not load type 'UnityEngine.InputForUI.Event' from assembly 'UnityEngine.InputForUIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[Message:UnityExplorer] [UniverseLib] Can't cache type named MethodInfoStoreGeneric_Map_Private_TOutputType_0`2 Error: System.TypeLoadException: Could not load type 'UnityEngine.InputForUI.Event' from assembly 'UnityEngine.InputForUIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[Message:UnityExplorer] [UniverseLib] Can't cache type named MapAsTimestamp Error: System.TypeLoadException: Could not load type 'UnityEngine.InputForUI.Event' from assembly 'UnityEngine.InputForUIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[Message:UnityExplorer] [UniverseLib] Can't cache type named MapAsPlayerId Error: System.TypeLoadException: Could not load type 'UnityEngine.InputForUI.Event' from assembly 'UnityEngine.InputForUIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
```

**Comment by originalnicodr** [comment]
I have the feeling that this has to do with the version of Unity the game runs on is one of the lasts, which might not be supported by new modloaders yet?

In any case I would give bepinex new version a try, or maybe try melon loader instead.

Let me know how it goes, and sorry it took me so long to get back to you!

**Comment by 2hac** [comment]
I use unity 2023.2.8f1 Ive used all latest versions of Mellon loader AND bepinx

**Comment by plasmatank** [comment]
Unity 6000.0.15f1, all the same
